### ISSUE TITLE
CLI doesn't exit (return control to the shell)

### ISSUE THREAD

**Issue by spikeliu** [seung-lab/igneous#102]
I installed the latest version of igneous and try to use the CLI to do simple job like downsampling, after I followed the instruction on the README page to create tasks and excute it, the log information would stop refreshing at some point showing something like "INFO FunctionTask 23a62836-1dbc-4350-9872-5dc8f6d06a96 succesfully executed in 18.43 sec." and never go back to shell, I can only exit the process by ctrl+c.

But I also tried to use the python interface as a simple script to do the same job, and it successfully finished. 

I did my test on "CentOS Stream 8" and I installed the package using pip. Could you tell me if it is normal or what I should do to correctly use the CLI? Thanks a million.

**Comment by william-silversmith** [comment]
Hi, I'm still working the kinks out of the CLI. `igneous execute` was designed for cluster use with huge jobs that you kill by deallocating the machine resources when it's finished. When used with SQS, it's not simple to decide when to stop as the queue only gives approximate statistics. With FileQueue, determining if the queue is empty is much simpler and maybe I should design around that.

However, `igneous execute` has a flag `--min-sec` that you can use to tell it how long to go before allowing itself to exit. The default is infinite execution, but `igneous execute $QUEUE --min-sec 600` will run for 10 minutes and exit. If the last task takes 3 hours, it will exit after the task completes.

**Comment by spikeliu** [comment]
I see it, so I will stick to the python script interface for now as it works as a charm. Thanks for your help.
