### ISSUE TITLE
neuroglancer can not show meshes

### ISSUE THREAD

**Issue by spikeliu** [seung-lab/igneous#104]
Sorry for asking many questions recently, but I am really try to learn more about these fancy tools. This time I created a simple 10 * 10 * 10 volume (this step seems not necessary as segmentation is a separate layer), and then make a segmentation vol with the same shape and assign seg[(1,2), (1,2), :] = 2, which means there is only one non zero id segmentation with ID number 2. Then I used the python script to do a two-step mesh generation task as the intruction in README.md.  When I tried to use neuroglancer to view the segmenation layer (data servered by launching cors_webserver.py), the 2D part works fine, but the mesh could not be displayed. I tried different versions of neuroglancer, including local version, [https://neuromancer-seung-import.appspot.com](https://neuromancer-seung-import.appspot.com) and [https://neuroglancer-demo.appspot.com](https://neuroglancer-demo.appspot.com), but they all failed to show the mesh. I also tried to delete the info in the mesh folder and use #type=mesh when providing the address, but still not fix the problem. I didn't use any compress flag when creating all data. To validate if the data was created correctly, I used cloudvolume to retrieved this mesh with ID 2 and save it as an obj file, it can be showed in other tools, though it is not a perfect cube as I thought it would be (I will put a snapshot of it below).
Do I miss any important information about meshes in neuroglancer? Can anyone help me figure out what is wrong.
The snapshot of the obj file:
![image](https://user-images.githubusercontent.com/5734885/124955539-b3e07c00-e049-11eb-8f34-bc54b19dbd7f.png)

The info in the segmentation folder and the one in the mesh folder are pasted below.
info file of segmentation:
```
{
  "data_type": "uint64",
  "mesh": "mesh_mip_0_err_40",
  "num_channels": 1,
  "scales": [
    {
      "chunk_sizes": [
        [
          1024,
          1024,
          1
        ]
      ],
      "compressed_segmentation_block_size": [
        8,
        8,
        8
      ],
      "encoding": "compressed_segmentation",
      "key": "500_500_500",
      "resolution": [
        500,
        500,
        500
      ],
      "size": [
        10,
        10,
        10
      ],
      "voxel_offset": [
        0,
        0,
        0
      ]
    }
  ],
  "type": "segmentation"
}

```
info file in mesh dir:
`{"@type":"neuroglancer_legacy_mesh","mip":0,"chunk_size":[1024,1024,1024],"spatial_index":{"resolution":[500,500,500],"chunk_size":[512000,512000,512000]}}`

The snapshot of the neuroglancer shows that the 2D segmentation is displayed, but there is no 3D meshes in the 3D pannel(left-buttom), the _**meshes**_ box is checked:
![image](https://user-images.githubusercontent.com/5734885/124956055-2cdfd380-e04a-11eb-89d1-7bac01ba6e58.png)

**Comment by william-silversmith** [comment]
Hi spike!

If you didn't provide a compression flag, it was probably gzipped by default. CloudVolume writes meshes to disk that are gzipped with a `.gz` extension. Instead of using the cors webserver script, try doing the following:

```python
from cloudvolume import CloudVolume
cv = CloudVolume(...)
cv.viewer()
```

This will launch a web server that understands how to read those extensions.

I'm also holding office hours at 3pm tomorrow. You're welcome to come (or keep posting issues here)! https://calendly.com/will-silversmith-office-hours/office-hours 

Will

**Comment by spikeliu** [comment]
Sorry for the unclear description about _compress_ flag, I set all of them to False to make sure no compression was made. Anyway, I figured out where the problem was, I put data on windows and it doesn't allow file names to have colons. Thanks a lot for those hints. Finally!!!
Another little question, though I can see the mesh in the example, but I have to double click the corresponding segmentation to make it appear, but when I look at some public costumized neuroglancer, those meshes are automatically displayed when the page is loaded. How to change this behavior?

**Comment by william-silversmith** [comment]
Hi Spike! Sorry I took a few days to get back to you. I'm not entirely sure how some of these other sites do it, but I can say that the selected segids should be saved in the URL. If you share the long URL they should appear!

**Comment by spikeliu** [comment]
I am not familiar with web programming and related knowledge, but managed to use the python api of neuroglancer to generate the long url with the mesh ids that I want to show by default. Now I'm curious is there any other way (an easier or more common way) to generate such a url. Maybe there is a way to store the configuration in a file like json format, and neuroglancer provides an existing way to parse it and append necearray information to the basic url when setting up a server oneself, but I didn't know?

**Comment by william-silversmith** [comment]
Hi Spike, how many ids are you talking? If it's just a few, you can enter them manually and copy paste the URL.

**Comment by spikeliu** [comment]
Wow, how didn't I realize that. Yeah, I can just open any public neuroglancer and edit most of the layout interactively and share the url in the address bar. Thanks a million again for your patient help.
