### ISSUE TITLE
[feature request] change parameter in command line while execution

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/igneous#11]
Sometimes, I would like to change parameters at the middle of a run. For example, I would like to switch to 4 core machines from 2 core machines and I need to change the parameter of network file, but the parameter was hard coded in the tasks. 

It would be nice to have this capability. It is not urgent though.

**Comment by william-silversmith** [comment]
You might be able to do this with environment variables. You can recreate a
deployment with the right env

**Comment by jingpengw** [comment]
ok, close now.
