### ISSUE TITLE
mesh misalignments and open faces

### ISSUE THREAD

**Issue by Martiantian** [seung-lab/igneous#118]
Hello, thank you very much for your tool providing a way to generate a mesh. I noticed a few things when I tried it.
1. The rendered mesh and section look misaligned.
![image](https://user-images.githubusercontent.com/35797239/150107070-3d39360e-462a-4d86-8add-62f0dac78867.png)

2. It looks like each data point will generate the corresponding octahedral vertices and then connect the outer contours.  But at the edge of space there will be open phenomenon.

![image](https://user-images.githubusercontent.com/35797239/150107323-0faa6c5b-a04e-48e8-9644-bfb3331d29eb.png)

![image](https://user-images.githubusercontent.com/35797239/150107138-a615770e-048f-43fc-8799-121b80acf041.png)

Looking forward to your reply

**Comment by william-silversmith** [comment]
Hi @Martiantian, thanks for writing in! 

The first example shouldn't happen. Recently, I created misalignments like that when creating sharded meshes. If that's the case, you can fix that by upgrading [DracoPy](https://github.com/seung-lab/DracoPy) to the latest version which has a special mode for integer meshes. Could you share the procedure you used to create the meshes?

The open faces are by design. That is what allows us to easily stitch together adjacent mesh tasks in large volumes. If you prefer closed faces, you can either enlarge the volume by one pixel on each side prior to meshing or you can use a library like trimesh to close the sides of the finished meshes.

Will

**Comment by Martiantian** [comment]
Thank you for your prompt reply.
I checked the data , the DracoPy version is 1.0.1 and Python version is 3.8.12.
The mesh is generated as follows: 
First  I create an array of dimensions (10,10,4)  by numpy , where [2:5,2:5,1:3], [2,8,1], [7,7,1:3] are assigned.
Then I use cloud-volume to convert to precomputed format and use Igneous to generate mesh. 
![image](https://user-images.githubusercontent.com/35797239/150262410-8927d93d-2919-4acc-a34f-67a67910dcc8.png)

**Comment by william-silversmith** [comment]
The only unusual part of that seems to be the `simplification_error=0`. Would you mind trying it again without that and seeing if it looks better? We usually use 40.

**Comment by Martiantian** [comment]
I tried the adjustment you mentioned, but it didn't work.Could this problem be related to the  neuroglancer version ?

**Comment by william-silversmith** [comment]
It's possible...  but this has been working with neuroglancer for years. Ah! I see one other thing that shouldn't cause issues but does trigger a different code path. Can you try using the default shape=(448,448,448)? Shapes greater than (1023, 1023, 511) on any dimension trigger a different processing mode in zmesh.

**Comment by Martiantian** [comment]
I don't know if this is normal or not, the misalignments are not solved after changing the parameters, and the mesh becomes strange.The original data is attached. You can try to see if you can reproduce the problem.
![image](https://user-images.githubusercontent.com/35797239/150757278-b1ff5e9d-3a9e-4ef2-bc10-cc816df11b28.png)
![1643016874(1)](https://user-images.githubusercontent.com/35797239/150757590-4856bb01-19be-42dc-978c-879ae8bb60fd.png)
![1643016914(1)](https://user-images.githubusercontent.com/35797239/150757681-a446c911-c0da-438d-9e97-b06273f906a4.png)
[segmentation.tar.gz](https://github.com/seung-lab/igneous/files/7924359/segmentation.tar.gz)

**Comment by william-silversmith** [comment]
Thank you for the data! That will help me a lot in reproducing the issue. I'll take a look hopefully later today.

**Comment by william-silversmith** [comment]
Hi I am looking into this and discussing with my colleagues. zmesh uses an interpolation scheme that ends up shifting the vertices by half a voxel which causes a contraction on one end. I am trying to understand the other side, but I suspect that it shifts the other end forward by half a voxel as well to preserve volume. 

Your segmentation uses a large voxel size (for us) of 500,500,500 whereas a typical size for us when meshing is 32,32,40 which may be causing the small difference to become more noticeable. Once I'm confident this is the correct analysis, it is possible we may integrate a half-voxel shift into zmesh or igneous.

**Comment by william-silversmith** [comment]
I have a patch for zmesh: https://github.com/seung-lab/zmesh/pulls/22 

I'll need to discuss this patch with some of my colleagues as it will break compatibility with their real time meshing jobs that are ongoing with proofreading efforts. Thank you for bringing this to our attention!

**Comment by william-silversmith** [comment]
I'm discussing the open/closed faces with my colleagues. I think it should at least be possible to have an option for this in igneous.

**Comment by Martiantian** [comment]
Thank you very much for your continuous attention to these two issues, and I will also spare some time to test the influence of voxel size you mentioned.

**Comment by william-silversmith** [comment]
Hi! So, I'm not quite ready to make a new release yet (we might decide to make one feature or the other non-default to preserve backwards compatibility) but the current master branch should solve both of these issues for you if you install it from github rather than PyPI. I'll make a new docker image too once we make a release (probably next week sometime).

**Comment by Martiantian** [comment]
I tried to install the latest version from github, and the problem was resolved. Thank you very much!
![image](https://user-images.githubusercontent.com/35797239/151656357-94e81d06-5be8-4874-8811-e4bfeacbd42d.png)
