### ISSUE TITLE
Two Jobs One Queue?

### ISSUE THREAD

**Issue by j6k4m8** [seung-lab/igneous#120]
So far I've tested this out and things seem to behave correctly, but I'm wondering if I'm just lucky and missing a race condition. I want to schedule many jobs simultaneously. Can I reuse the same queue for all of these?

```bash
$ igneous downsample foo --num-mips 4 --queue fq://my-queue
$ igneous downsample bar --num-mips 4 --queue fq://my-queue
$ igneous execute fq://my-queue
```

(I realize that this definitely doesn't guarantee that `foo` will finish before `bar` begins!)

Will there be collisions here, or does each queue item get all the information it needs to operate independently and without conflicts?

**Bonus Round:**

```bash
$ igneous downsample foo --num-mips 4 --queue fq://my-queue
$ igneous execute fq://my-queue &
$ igneous downsample bar --num-mips 4 --queue fq://my-queue
```

Can I execute a queue and then continue adding to it while it's already executing?

**Comment by william-silversmith** [comment]
Hi Jordan! I typically don't do this, but there's no reason the queue wouldn't work fine with intermixed items. If one job runs into problems it could lock the second job, but hopefully that won't happen at all.

You should be able to add to the queue as well. If you have multiple adds to an `fq://` queue running simultaneously some of the queue statistics can be corrupted (I'm thinking of "inserted" specifically) if they race to update that number.

**Comment by j6k4m8** [comment]
Super cool, thanks for the fast and detailed response! Going to give this a whirl shortly and I will report back if anything unexpected and catastrophic happens :)

**Comment by j6k4m8** [comment]
Update: This does exactly what one would expect :) Thank you!!
