### ISSUE TITLE
Missing parameter for MultiResShardedFromUnshardedMeshMergeTask

### ISSUE THREAD

**Issue by Mencu** [seung-lab/igneous#133]
Hey, 

I've noticed there is no `min_chunk_size` parameter given to the [MultiResShardedFromUnshardedMeshMergeTask](https://github.com/seung-lab/igneous/blob/master/igneous/tasks/mesh/multires.py#L245). The parameter is used later in [create_mesh_shard](https://github.com/seung-lab/igneous/blob/master/igneous/tasks/mesh/multires.py#L266), which gives an error - not defined. 

Best,
Andrei

**Comment by william-silversmith** [comment]
I'm also going to add very basic support for unsharded multires, but it's not going to be by any means complete at the moment. This means that you'll be able to transfer only the highest res LOD for now. I'll need to add special logic for that in the future.

**Comment by william-silversmith** [comment]
This should be fixed in Igneous 4.2.1. Please reopen if you still have issues.
