### ISSUE TITLE
cloudfiles.exceptions.DecompressionError: File contains zero bytes: N/A

### ISSUE THREAD

**Issue by manoaman** [seung-lab/igneous#141]
Hi,

I'm observing `cloudfiles.exceptions.DecompressionError: File contains zero bytes: N/A` during TransferTask (igneous image xfer).  Is there a way to avoid this error in Igneous?

There seems to be a few zero byte chunk files generated from CloudVolume before reaching this step.  And I suppose these may have been black background that I see in the original image slices.  Would it help to configure `fill_missing=True` and/or `delete_black_uploads=True` at CloudVolume step to avoid zero byte chunks?

Thanks,
-m

**Comment by manoaman** [comment]
The black background tiles are in fact empty data from the original image that I see.  Perhaps it is okay to proceed with Igneous TransferTask while DecompressionError is thrown?

**Comment by william-silversmith** [comment]
Hi m,

I would use fill_missing=True for this problem.

**Comment by manoaman** [comment]
Fantastic, I believe this prevented the issue generating zero byte chunk files with CloudVolume.  Thank you!!

**Comment by william-silversmith** [comment]
Glad that helped!
