### ISSUE TITLE
`num_mips` needs a type annotation

### ISSUE THREAD

**Issue by j6k4m8** [seung-lab/igneous#161]
https://github.com/seung-lab/igneous/blame/ee15a88d6c19f60b4dfb68ed192010ff3bf0866b/igneous_cli/cli.py#L192

Specifying `num_mips` since this commit now results in an op error, since it's being interpreted as a str.... I think!

cc @dxenes1

**Comment by william-silversmith** [comment]
Oh interesting, thank you for the bug report! I'll fix this now.

**Comment by j6k4m8** [comment]
Speeeeeeedy!!! Thank you :D
