### ISSUE TITLE
Do I need to manually clear the folder where QUEUE is stored?

### ISSUE THREAD

**Issue by liuyx599** [seung-lab/igneous#163]
I tried running the following command, I've noticed that this QUEUE folder is taking up a lot of space on hard drive, 
should I use the `rm -rf QUEUE/*` command to clean it up before each script use?

On the one hand I'm worried about the space it takes up as I use the script more and more, and on the other hand I'm worried about all the commands (e.g. generating mesh and skeleton all in the same QUEUE directory, and whether there will be any conflicts), but of course if `igneous` could handle such doubts automatically I might not have to worry so much. 

As we all know, `rm -rf` is a very dangerous command that I wouldn't dare to use on a server cluster

```sh
rm -rf $QUEUE/*   # if needed?
igneous mesh forge $SEGPATH --dir mesh  --mip 2 --queue $QUEUE --sharded
igneous --parallel 8 execute $QUEUE
igneous mesh merge-sharded $SEGPATH --queue $QUEUE
igneous execute $QUEUE
```

**Comment by william-silversmith** [comment]
Hi! 

Yes, it is advisable to clear the queue when it is completed. Instead of using `rm -rf` you can use the safer `ptq purge DIRECTORY` command that comes installed with igneous. ptq stands for "python task queue".

**Comment by liuyx599** [comment]
i got it, thank you very much!
