### ISSUE TITLE
Image create command crashes for path including "."

### ISSUE THREAD

**Issue by jakobtroidl** [seung-lab/igneous#168]
This is a minor problem, but I thought I share it since I spent my last hour on it. It seems like the `igneous image create` command crashes if there is a `.` in the filename of the `.npy` file. For example, this command throws an error message `format not supported`: 

```
igneous image create ./my.test.npy ./PRECOMPUTED_FOLDER --compress none
```
whereas this works

```
igneous image create ./my_test.npy ./PRECOMPUTED_FOLDER --compress none
```

**Comment by jakobtroidl** [comment]
Maybe to avoid future confusion [this line](https://github.com/seung-lab/igneous/blob/37cd4fc9a42a1d698d21755945b6a39cadad5bff/igneous_cli/cli.py#L1662) could be updated to 

```python
print("Format not supported: {}".format(ext))
```
I can submit a PR if you want @william-silversmith.

**Comment by william-silversmith** [comment]
Thank you for reporting this! I pushed a fix. I'm working on something skeleton related, but I'll push a new PyPI release soon.
