### ISSUE TITLE
[feature request] sparse meshing

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/igneous#18]
In zebrafish, the meshing takes a few days. Sometimes there is some tasks left and I have to rerun the whole thing to get it done. 
Actually, we only need to mesh the reconstructed cells, meaning sparse meshing. 
It would be nice to have this capability?

**Comment by nkemnitz** [comment]
@jingpengw: You might be able to use the `remap_table` argument for what you are planning. It's a dictionary you can pass to MeshTask that will cause igneous to relabel segment IDs in your segmentation layer prior to calling Marching Cubes. We use it for the ChunkedGraph when creating agglomerated meshes from the watershed segmentation layer, where many supervoxel IDs need to be mapped to a few agglomeration IDs.
As a side effect, everything not specified in the remap table gets treated as black/boundary. So, if you pass a remap table that only contains completed cell IDs, and map each ID back onto itself... you essentially black out everything you do not want to generate a mesh for.

Caveat: The remap tables can get quite large - too large for an SQS payload (300kB)

**Comment by william-silversmith** [comment]
Fwiw, the old school way of doing the remap tables was to upload a file to GCS and download and cache it locally. That way you don't send unwieldy json files through SQS.

**Comment by jingpengw** [comment]
sounds great! Will have a try in the next run.

**Comment by jingpengw** [comment]
working on it here:
https://github.com/seung-lab/igneous/issues/18

**Comment by jingpengw** [comment]
not super necessary, close here.
