### ISSUE TITLE
register igneous to pip?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/igneous#41]
I need to use some functions from igneous, it would be easier to make travis tests if igneous was registered.

**Comment by william-silversmith** [comment]
Can you describe your use case a bit more?

**Comment by jingpengw** [comment]
I am using the downsample_and_upload function, and I need to import it from igneous.

**Comment by jingpengw** [comment]
@william-silversmith I can help to register if you would like?

**Comment by william-silversmith** [comment]
Hmm, maybe we should break out the downsample logic into either its own package or into a CloudVolume submodule. It's all python/numpy so it wouldn't present much of a burden for others using CloudVolume. I was thinking of breaking out Zlateski's mesher as well.

**Comment by jingpengw** [comment]
that's a great idea, many of the functions are generally useful.
please let me know if I can do any help.

Jingpeng Wu
Postdoc of Princeton University
jingpeng@princeton.edu (https://link.getmailspring.com/link/1550662169.local-b32e9363-78ff-v1.5.6-4cb1851b@getmailspring.com/0?redirect=mailto%3Ajingpeng%40princeton.edu&recipient=cmVwbHkrMDA3NGMwZjViNTI4N2JjYzZjNzE0NWRlZTAzNDdlODI5YWViNGM5ODJjMDBhNjYzOTJjZjAwMDAwMDAxMTg4NGQwZWI5MmExNjljZTE4MTMzZWQxQHJlcGx5LmdpdGh1Yi5jb20%3D)
http://jingpengw.com (https://link.getmailspring.com/link/1550662169.local-b32e9363-78ff-v1.5.6-4cb1851b@getmailspring.com/1?redirect=http%3A%2F%2Fjingpengw.com&recipient=cmVwbHkrMDA3NGMwZjViNTI4N2JjYzZjNzE0NWRlZTAzNDdlODI5YWViNGM5ODJjMDBhNjYzOTJjZjAwMDAwMDAxMTg4NGQwZWI5MmExNjljZTE4MTMzZWQxQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by william-silversmith** [comment]
A good deal of the downsampling code now resides in https://github.com/seung-lab/tinybrain

**Comment by william-silversmith** [comment]
Demand for this seems to have been reduced as of late. @jingpengw is there anything else you'd like to be broken out before I close?

**Comment by jingpengw** [comment]
thanks for the tinybrain, I can delete the copied code now. 
the next step is breaking out mesher?

**Comment by william-silversmith** [comment]
The mesher is currently undergoing some upgrades. A few people are asking about it so it's a good candidate for breaking it out.

**Comment by william-silversmith** [comment]
https://github.com/seung-lab/zmesh is now available. Anything else?

**Comment by jingpengw** [comment]
good enough for now! thanks again!
