### ISSUE TITLE
Mesh Brotli Support

### ISSUE THREAD

**Issue by cnzqy1** [seung-lab/igneous#65]
In CloudVolume there is a  `compress` argument that allows output of brotli compressed files. However, I do not see such an argument in Igneous, and I always get gzip compressed files. Is there a way to get brotli compressed files?

**Comment by william-silversmith** [comment]
Thanks for writing in! CloudVolume currently supports brotli for AWS S3 and the filesystem, but not for Google Cloud Storage due to some limitations in the underlying library (https://github.com/seung-lab/cloud-volume/issues/283). Most of our stuff is on GCS so I haven't had a lot of motivation to integrate an option into Igneous up to this point. Would you be able to benefit from brotli support? What tasks are you thinking of using?

**Comment by cnzqy1** [comment]
Thanks for your reply! We have relatively small datasets so they are all processed and served locally. Since brotli is a better compression algorithm I was thinking about just serving all data as brotli compressed. I was modeling after the workflow in seung-lab/cloud-volume#319 and it involves final steps in Igneous, which generates gzip files in the end.

**Comment by william-silversmith** [comment]
Downsample and Transfer tasks now have a "compress" argument. Let me know if this doesn't resolve your problem. ^_^

**Comment by cnzqy1** [comment]
Thanks a lot! When I run:

from taskqueue import LocalTaskQueue
import igneous.task_creation as tc

src_layer_path = 'file://output'
dest_layer_path = 'file://output2'

with LocalTaskQueue(parallel=16) as tq:
  tasks = tc.create_transfer_tasks(
    src_layer_path, dest_layer_path, 
    chunk_size=(64,64,64), shape=(256,256,256), skip_downsamples=True, compress='br'
  )
  tq.insert_all(tasks)

I got the error 

> Traceback (most recent call last):
  File "rechunk_and_downsample.py", line 8, in <module>
    tasks = tc.create_transfer_tasks(
TypeError: create_transfer_tasks() got an unexpected keyword argument 'compress'

Did I do something wrong?

**Comment by william-silversmith** [comment]
Whoops, download the latest and try again!

**Comment by cnzqy1** [comment]
I can confirm that it works great, thanks again! Would you mind also adding brotli support to the meshing function as well when you get a chance?

**Comment by william-silversmith** [comment]
Brotli support added ^_^

**Comment by cnzqy1** [comment]
I'm really sorry to bother you again, but when I run:

```
with LocalTaskQueue(parallel=8) as tq:
  tasks = tc.create_meshing_tasks(layerpath, mip=0, dust_threshold=10, compress='br')
  tq.insert_all(tasks)
```

I still get gzip files. Did I do something wrong?

**Comment by william-silversmith** [comment]
Oops, I tested MeshTask but not task creation. I accidentally used a literal instead of a variable. Fixed!
