### ISSUE TITLE
Somewhat unusual workflow

### ISSUE THREAD

**Issue by cnzqy1** [seung-lab/igneous#70]
We are planning to manually segment some data, and to reduce the amount of time for reconstruction we are going to segment a downsampled volume. The workflow I'm currently thinking is:

Raw EM data (4x4x4 nm) -> downsample to 16x16x16 nm -> segment at 16x16x16 nm -> upscale segmentation to 4x4x4 nm w/ nearest neighbor -> generate meshes at 4x4x4 nm -> combine upscaled segmentation and meshes with raw EM data and visualize in Neuroglancer

I'm hoping to use Igneous for many of these steps, and I have a few questions:

1. I saw that a new option `factor` is being added to the downsampling function. Does that mean I can directly downsample from 4x4x4 to 16x16x16 for the raw EM data?

2. I don't think I saw an upscaling function in Igneous, could you confirm that there isn't such a function?

3. Is it possible to directly generate meshes with 16x16x16 segmentation data and display them properly in the 4x4x4 dataset? (instead of upscaling and then generating meshes at 4x4x4)

Thank you very much for your help!

**Comment by william-silversmith** [comment]
Hi thanks for writing in! Yes, Igneous will support most of these steps.

> I saw that a new option factor is being added to the downsampling function. Does that mean I can directly downsample from 4x4x4 to 16x16x16 for the raw EM data?

Yes. Make sure to use `factor=(2,2,2)` with `num_mips=2 (or greater)` to take advantage of the speed and precision of [tinybrain](https://github.com/seung-lab/tinybrain/). I'm working on factor right now, so if you run into problems, please let me know. Previously we supported (2,2,1) downsamples efficiently, now (2,2,2) downsamples are supported. Arbitrary downsamples are supported by may be slow and memory hungry. 

> I don't think I saw an upscaling function in Igneous, could you confirm that there isn't such a function?

There is no such function in Igenous currently. Some other projects in the lab have performed upsampling in the past. If you'd like to contribute a function, I'd be happy to accept it. :)

> Is it possible to directly generate meshes with 16x16x16 segmentation data and display them properly in the 4x4x4 dataset? (instead of upscaling and then generating meshes at 4x4x4)

Yes, in fact it is typical for us to run meshing on 32x32x40 (mip 3) for a 4x4x40 (mip 0) dataset. The meshes display naturally in neuroglancer.

**Comment by cnzqy1** [comment]
Thanks a lot for your help!

> Yes. Make sure to use `factor=(2,2,2)` with `num_mips=2 (or greater)` to take advantage of the speed and precision of [tinybrain](https://github.com/seung-lab/tinybrain/). I'm working on factor right now, so if you run into problems, please let me know. Previously we supported (2,2,1) downsamples efficiently, now (2,2,2) downsamples are supported. Arbitrary downsamples are supported by may be slow and memory hungry.

We are also considering downsampling by a factor of 3 for certain datasets. Would that be inadvisable?

> There is no such function in Igenous currently. Some other projects in the lab have performed upsampling in the past. If you'd like to contribute a function, I'd be happy to accept it. :)

I'd love to but unfortunately I don't know much Python (I do most coding in Matlab) and am still relatively new to image processing.
 
> Yes, in fact it is typical for us to run meshing on 32x32x40 (mip 3) for a 4x4x40 (mip 0) dataset. The meshes display naturally in neuroglancer.

That's good to know! I'll give that a try.

I'll run this workflow on a small test dataset and see if there are issues.

**Comment by cnzqy1** [comment]
I did run into an issue with TransferTask:

> Traceback (most recent call last):
>   File "rechunk_and_downsample.py", line 9, in <module>
>     tasks = tc.create_transfer_tasks(
>   File "/home/cnzqy1/igneous/igneous/task_creation.py", line 935, in create_transfer_tasks
>     create_downsample_scales(dest_layer_path,
> NameError: name 'create_downsample_scales' is not defined

**Comment by william-silversmith** [comment]
>  We are also considering downsampling by a factor of 3 for certain datasets. Would that be inadvisable?

It should work, but you may be surprised by the decrease in performance. Only 2x2 and 2x2x2 are specially tuned.

> I'd love to but unfortunately I don't know much Python (I do most coding in Matlab) and am still relatively new to image processing.

That's okay! I'm glad you're finding Igneous useful. :)

> I did run into an issue with TransferTask:

Thanks that's an easy fix! I'll upload it now.

**Comment by cnzqy1** [comment]
Thanks for the fix! When I downsample using the `factor` option, I got the non-aligned writes error:

> Traceback (most recent call last):
>   File "downsample_for_segmentation.py", line 10, in <module>
>     tq.insert_all(tasks)
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/taskqueue/taskqueue.py", line 600, in insert_all
>     self._process(progress)
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/taskqueue/taskqueue.py", line 616, in _process
>     _task_execute(self.queue.pop(0))
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/taskqueue/taskqueue.py", line 636, in _task_execute
>     task.execute(*args, **kwargs)
>   File "/home/cnzqy1/igneous/igneous/tasks/tasks.py", line 758, in execute
>     downsample_and_upload(
>   File "/home/cnzqy1/igneous/igneous/tasks/tasks.py", line 83, in downsample_and_upload
>     vol[new_bounds] = mipped
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/cloudvolume/frontends/precomputed.py", line 756, in __setitem__
>     self.image.upload(img, bbox.minpt, self.mip, parallel=self.parallel)
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/cloudvolume/datasource/__init__.py", line 50, in guardfn
>     return fn(self, *args, **kwargs)
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/cloudvolume/datasource/precomputed/image/__init__.py", line 169, in upload
>     return tx.upload(
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/cloudvolume/datasource/precomputed/image/tx.py", line 62, in upload
>     is_aligned = check_grid_aligned(
>   File "/home/cnzqy1/.virtualenvs/ig/lib/python3.8/site-packages/cloudvolume/datasource/__init__.py", line 66, in check_grid_aligned
>     raise exceptions.AlignmentError(msg)
> cloudvolume.exceptions.AlignmentError:

I don't get this error if I leave out the `factor` argument.

**Comment by william-silversmith** [comment]
You have to set the `shape` parameter to be a multiple of the chunk_size and the factor size.

**Comment by cnzqy1** [comment]
I just want to clarify, should the `shape` parameter be directly passed to the `create_downsampling_tasks()` function? I got the following error:

> TypeError: create_downsampling_tasks() got an unexpected keyword argument 'shape'

**Comment by william-silversmith** [comment]
Oh, sorry! I thought you were using TransferTasks. `shape` is only an argument there. What parameters were you using? I just ran downsample tasks and didn't run into a problem.

**Comment by cnzqy1** [comment]
I think I found out the actual issue: having just 4_4_4 to begin with works fine, but if I have 4_4_4, 8_8_4, and 16_16_4 in the folder, Igneous throws this error instead of generating 8_8_8 and 16_16_16. Maybe this is the expected behavior? If so it's just a minor inconvenience and probably doesn't need changing.

**Comment by cnzqy1** [comment]
I think I got all parts of this workflow worked out. Thanks again for your help!
