### ISSUE TITLE
Python syntax warning

### ISSUE THREAD

**Issue by cnzqy1** [seung-lab/igneous#71]
There is a syntax warning I encountered:

```
igneous/igneous/chunks.py:35: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (shape is None or dtype is None) and encoding is not 'npz':
```

Doesn't break anything at the moment but looks like a simple fix.

**Comment by william-silversmith** [comment]
Should be fixed in 6b93a3dfd21047d3967f3ddb5a8f4e0a569e11a1 Thank you!
