### ISSUE TITLE
Downsampling 2x2x2?

### ISSUE THREAD

**Issue by albertplus007** [seung-lab/igneous#74]
Hi, igneous team
I see the igneous can downsample dataset
```python3
tasks = create_downsampling_tasks(
    layer_path, # e.g. 'gs://bucket/dataset/layer'
    mip=0, # Start downsampling from this mip level (writes to next level up)
    fill_missing=False, # Ignore missing chunks and fill them with black
    axis='z', 
    num_mips=5, # number of downsamples to produce. Downloaded shape is chunk_size * 2^num_mip
    chunk_size=None, # manually set chunk size of next scales, overrides preserve_chunk_size
    preserve_chunk_size=True, # use existing chunk size, don't halve to get more downsamples
    sparse=False, # for sparse segmentation, allow inflation of pixels against background
    bounds=None, # mip 0 bounding box to downsample 
    encoding=None # e.g. 'raw', 'compressed_segmentation', etc
    delete_black_uploads=False, # issue a delete instead of uploading files containing all background
    background_color=0, # Designates the background color
    compress='gzip', # None, 'gzip', and 'br' (brotli) are options
  )
```
I see it just downsample the dataset `2x2x1`, if the dataset's size is `256x256x256` it will get a `128x128x256`.
So how to get a `2x2x2` downsample, for example: the dataset's size is `256x256x256` it will get a `128x128x128`.

**Comment by william-silversmith** [comment]
Hi Albert,

I just updated the documentation. We recently added a "factor" option that lets you specify (2,2,1), (2,2,2), etc. Note that (2,2,1) and (2,2,2) are treated specially in https://github.com/seung-lab/tinybrain/ in that pains are taken to avoid integer truncation, give high performance, and in some cases, support the sparse flag.

Resolved in e07297

**Comment by albertplus007** [comment]
Another question, if I use the google segmentation, such as `4x4x40nm` resolution, and use this function to downsample the dateset to `8x8x40nm`, does the same result of mine (use `4x4x40nm` to get `8x8x40nm`) as the dataset of google segmentation on `8x8x80nm`?

**Comment by william-silversmith** [comment]
It's possible, but I doubt it unless they are also downsampling using the mode of 2x2 instead of striding. If they are using the mode, they are probably also doing it "correctly" so that the mode of mip 2 to N is based on mip 0, whereas we compute it recursively. One day I might fix this.

**Comment by albertplus007** [comment]
Ok, I see in low resolution there are lots of neurons broken, but they are well preserved at high resolution, but you know high resolution result data volume is too large, so i want to downsample the high resolution to low resolution

**Comment by albertplus007** [comment]
I am still confusing that using this library to downsample the dataset, can we maintain the dataset continuity?
How many times downsampling will this problem occur? In low resolution there are lots of neurons broken, but they are well preserved at high resolution.

**Comment by william-silversmith** [comment]
Hi Albert,

Generally things seem to work ok at 32x32x40 and still work but neurites
are very thin at 64x64x40. I wouldn't go higher than that for any kind of
analysis that requires intact neurites.

**Comment by william-silversmith** [comment]
I'm gonna close this issue as I think the question has been answered. Reopen or open a new issue if you think you need to! Happy downsampling. :)
