### ISSUE TITLE
DeleteTask follows redirects, potentially deleting important data

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/igneous#84]
With the current behavior, the delete task just keeps following the redirect key specified in the info file. That's definitely bad - if you want to delete a dataset, the path provided should be unambiguous. And it prevents deleting the dataset that's masked by the redirect. (We do have such datasets)

Opening this issue to determine what the best approach is.
I would just pass `max_redirects=0` for `create_deletion_task` as well as `DeleteTask.execute()`, but maybe there is a better way?

**Comment by william-silversmith** [comment]
Oh dang, somehow I didn't notice this issue in my emails. Yes, that's the right way to do it Nico.
