### ISSUE TITLE
Help understanding non-aligned write error when downsampling

### ISSUE THREAD

**Issue by austinhoag** [seung-lab/igneous#87]
I have a volume representing a stack of images read out from a microscope. There are 687 2D images each of which have dimension 2160 x 2560. So the resulting volume has dimension [2160,2560,687] in x,y,z. At the full resolution this volume loads too slow in Neuroglancer to be usable so I have turned to downsampling. A successful downsampling scheme I have used is the following:

```
mip = 0, factor = [2,2,1], resulting dimension = [1080,1280,687]
mip = 1, factor = [2,2,1], resulting dimension = [540,640,687]
mip = 2, factor = [2,2,1], resulting dimension = [270,320,687] 
mip = 3, factor = [2,2,1], resulting dimension = [135,160,687]
```
I am using `chunk_size=[128,128,64]` for all mip levels.

The code structure I am using to do the downsampling is:
```python
mips = [0,1,2,3]
for mip in mips:
        cv = CloudVolume(rechunked_cloudpath, mip)
        chunks = calculate_chunks(downsample, mip) # uses the scheme mentioned above
        factors = calculate_factors(downsample, mip) # uses the scheme mentioned above
        tasks = tc.create_downsampling_tasks(cv.layer_cloudpath, 
                            mip=mip, 
                            num_mips=1, 
                            factor=factors,
                            preserve_chunk_size=False,
                            compress=True, 
                            chunk_size=chunks)
        tq.insert(tasks)
        tq.execute()
```

This works fine but I would like to downsample in z as well. Let's say I adopt the following downsampling scheme instead:

```
mip = 0, factor = [2,2,1], resulting dimension = [1080,1280,687]
mip = 1, factor = [2,2,1], resulting dimension = [540,640,687]
mip = 2, factor = [2,2,3], resulting dimension = [270,320,229] 
mip = 3, factor = [2,2,1], resulting dimension = [135,160,229]
```
The only difference is the `factor=[2,2,3]` in the mip=2 downsample, where I chose 3 because 687 is divisible by 3. The python code fails on this downsample level and gives me the following error:
```python
 Alignment Check:
    Mip:             3
    Chunk Size:      [128 128  64]
    Volume Offset:   [0 0 0]
    Received:        Bbox([0, 0, 192],[128, 128, 229], dtype=int32)
    Nearest Aligned: Bbox([0, 0, 192],[128, 128, 256], dtype=int32)
```
I don't understand what the problem is. It seems like there are some left over pixels in the z dimension so there is an incomplete chunk. But shouldn't this happen always unless your image size happens to be divisible by the chunk size? That's almost never the case. I didn't get this error when the z dimension was 687 for example. What is meant by "Aligned" in the error message?

I can strip off a z plane at the end to make the z dimension an even number but I'd ideally like to understand what is causing this issue. 

Thanks,
Austin

**Comment by william-silversmith** [comment]
Hi Austin, 

Igneous is only tested with z factors 1 and 2 (and is highly optimized for them, other factors will result in longer run times and higher memory usage). You are correct that exactly matching the number of chunks should be immaterial. Would you mind trying with 2 and let me know if that works?  I started looking into the factor 3 issue, but it looks like it will take some time to investigate. I'm currently on vacation, but I can possibly take a look next week. Happy to give advice in the meantime though!

Will

**Comment by austinhoag** [comment]
Hi Will, 

Thanks for getting back to me so quickly. Replacing [2,2,3] with [2,2,2] worked!
