### ISSUE TITLE
Compatibility of github repo and dockerhub image

### ISSUE THREAD

**Issue by chrisroat** [seung-lab/igneous#93]
Are the recent github code and dockerhub versions compatible?  I was browsing the commits of the last few months, and don't notice anything that looks breaking.

I am updating dependencies in my project, and ran into a conflict with oauth2client being pinned in the older version of igneous I was using.  My client code isn't fancy -- it's submitting transfer tasks with downsampling to an AWS queue.  My igneous cluster deploys an older igneous docker image, which reads from the queue.  

Previously I had pinned:
github commit: 2e1db31f60331420f72c958cedb7932a84fe6ef (2020/09/02)
dockerhub sha256: b359fce8e5b3e5061d6b4800fd61cd2b9b9c8c10e2b5f87f11984d1a3ee7cdfb (cannot locate)

Currently, the most recent versions are:
github commit: 823c9b1aebbcc660584e08c59159802e8749da23 (2021/05/15)
dockerhub sha256: 896dd8db6d7d3bf53bbe12623653eb6d4eb485fcb632ef5c426caa65b25d3ad3 (4 months ago)

I don't know how to tell at which the dockerhub image was built.  Are there any incompatibilities to be aware of if I jump to the newest versions?

Thanks in advance!

**Comment by william-silversmith** [comment]
Hi Chris,

The last dockerhub image should be mostly compatible, but there have been a
few minor changes. I'll release a new version sometime over the weekend.

Sorry about that, I usually release a new Igneous docker when I'm running
big jobs, but I've been tinkering with libraries for a few months.

Will

**Comment by william-silversmith** [comment]
Hi Chris,

I just pushed a new docker image. Sorry for the wait!

**Comment by chrisroat** [comment]
Thanks!  No problems or rush from my end.  Much appreciated.
